### ISSUE TITLE
Create tag

### ISSUE THREAD

**Issue by goralgen** [Magento2Translations/language_fr_fr#1]
Create please version in composer.json and tag for proper install by composer, e.g.
composer require magento2translations/language_fr_fr 0.0.1

**Comment by MrGekko** [comment]
There are no specific versions. If the crowdin language is updated the package will too.
You could require a specific commit, see: https://getcomposer.org/doc/04-schema.md#package-links
Or you could use the different branches in this git repo to specify for what magento version the translations are.
