### ISSUE TITLE
Incorrect row

### ISSUE THREAD

**Issue by goralgen** [Magento2Translations/language_fr_fr#2]
Please fix rows with phrase 'Captcha is case sensitive'
For example line should be 2 lines:
"* Required Fields","* Champs obligatoires""<strong>Attention</strong>: Captcha is case sensitive.",module,Magento_Wishlist

Expected:
"* Required Fields","* Champs obligatoires"
"<strong>Attention</strong>: Captcha is case sensitive.",module,Magento_Wishlist

**Comment by MrGekko** [comment]
Hi, thank you for using the package.
If you want to change lines, please do so at: https://crowdin.com/project/magento-2/fr#
Those translations will be added to this repo. I cant just change one line.
