### ISSUE TITLE
Contact Page is broken

### ISSUE THREAD

**Issue by lewisvoncken** [Magento2Translations/language_fr_fr#3]
Attention: Captcha is case sensitive." data-mage-init='{"validation":{}}'>

**Comment by tomsonnemans** [comment]
Probably is solved when the no-break characters and zero width characters are fixed.

**Comment by MrGekko** [comment]
Is it possible to change this in the Crowdin repo?
https://crowdin.com/project/magento-2/fr

**Comment by MrGekko** [comment]
I will close the issue because of inactivity... 
If you find a solution, I am happy to implement it.
